#!/usr/bin/env bash
set -euo pipefail

git config --global core.pager delta
git config --global interactive.diffFilter 'delta --color-only'
git config --global delta.navigate true
git config --global delta.light false
git config --global merge.conflictstyle zdiff3
git config --global diff.colorMoved default

echo "Configured global git delta defaults"
