#!/usr/bin/env julia
#
# Title: Julia Packages Installation
# Description: Install All Julia Packages that I use.
# Tags: Programming Language, Julia, Package
#

using Base.Pkg
Pkg.update()
Pkg.add("DataFrames")
Pkg.add("PyCall")
Pkg.add("Requests")
Pkg.add("JSON")
Pkg.add("Cairo")
Pkg.add("Gadfly")
Pkg.add("DecisionTree")
Pkg.add("JLD")
Pkg.add("Images")
Pkg.add("Immerse")
Pkg.add("Distributions")
Pkg.add("PyPlot")
Pkg.add("Winston")
Pkg.add("UnicodePlots")
Pkg.add("IJulia")
Pkg.add("Lumberjack")
Pkg.add("Compat")
Pkg.add("Interact")
Pkg.add)("LightGraphs")
