#!/usr/local/env bash

# MacOS programs installed at Brew

brew install macvim --override-system-vim
brew install mplayer
brew install tmux
brew install urlview 
brew install reattach-to-user-namespace
