#!/usr/bin/env julia
#
# Title: Julia Packages Installation
# Description: Install all Julia packages that I use.
# Tags: Programming Language, Julia, Package
#

using Pkg

packages = [
    "AbstractDomains",
    "ArgParse",
    "BackpropNeuralNet",
    "BayesNets",
    "BenchmarkTools",
    "BloomFilters",
    "Bootstrap",
    "Bokeh",
    "CRC",
    "CRF",
    "Cairo",
    "Calculus",
    "Clustering",
    "Color",
    "ColorBrewer",
    "Compat",
    "Compose",
    "ConfParser",
    "Convex",
    "CovarianceMatrices",
    "DataFrames",
    "DataFramesMeta",
    "DataStructures",
    "Debug",
    "Decimals",
    "DecisionTree",
    "DimensionalityReduction",
    "DirichletProcessMixtures",
    "Distances",
    "Distributions",
    "Documenter",
    "DocOpt",
    "EmpiricalRisks",
    "ExtremelyRandomizedTrees",
    "FiniteStateMachine",
    "FunctionalCollections",
    "FunctionalData",
    "GZip",
    "GLM",
    "GLMNet",
    "Gadfly",
    "GeoIP",
    "GeometricalPredicates",
    "GitHub",
    "GraphLayout",
    "GraphViz",
    "Graphs",
    "HDF5",
    "HTTP",
    "Humanize",
    "HypothesisTests",
    "IJulia",
    "ImageView",
    "Images",
    "Immerse",
    "Interact",
    "JLD",
    "JSON",
    "Lasso",
    "Levenshtein",
    "Lumberjack",
    "MLBase",
    "Markdown",
    "NBInclude",
    "NearestNeighbors",
    "NumericExtensions",
    "ProgressMeter",
    "PyCall",
    "PyPlot",
    "RCall",
    "RDatasets",
    "Reactive",
    "RegERMs",
    "SIUnits",
    "SQLite",
    "StatsBase",
    "TestImages",
    "Twitter",
    "UnicodePlots",
    "Vega",
    "XGBoost",
    "YAML",
    "kNN",
]

for pkg in packages
    Pkg.add(pkg)
end

Pkg.add(PackageSpec(url = "https://github.com/simonster/LIBSVM.jl"))
Pkg.add(PackageSpec(url = "https://github.com/anj1/NeuralNets.jl"))
Pkg.add(PackageSpec(url = "https://github.com/lepisma/ELM.jl"))

Pkg.update()
