return {
  { "nvim-tree/nvim-tree.lua", dependencies = { "nvim-tree/nvim-web-devicons" } },
  { "windwp/nvim-autopairs", event = "InsertEnter" },
  { "numToStr/Comment.nvim", config = true },
  { "folke/which-key.nvim", config = true },
  { "lukas-reineke/indent-blankline.nvim", main = "ibl", opts = {} },
  { "tpope/vim-surround" },
  { "nvim-lualine/lualine.nvim" },
  { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
  { "folke/tokyonight.nvim" },
  { "EdenEast/nightfox.nvim" },
  { "rebelot/kanagawa.nvim" },
  { "navarasu/onedark.nvim" },
  { "gruvbox-community/gruvbox" },
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  { "nvim-telescope/telescope.nvim", dependencies = { "nvim-lua/plenary.nvim" } },
  { "lewis6991/gitsigns.nvim" },
  { "williamboman/mason.nvim" },
  { "williamboman/mason-lspconfig.nvim" },
  { "neovim/nvim-lspconfig" },
  { "hrsh7th/nvim-cmp" },
  { "hrsh7th/cmp-nvim-lsp" },
  { "hrsh7th/cmp-buffer" },
  { "hrsh7th/cmp-path" },
  { "L3MON4D3/LuaSnip" },
  { "nvimtools/none-ls.nvim" },
  { "rcarriga/nvim-notify" },
  { "akinsho/toggleterm.nvim", config = true },
  { "stevearc/overseer.nvim" },
  { "mfussenegger/nvim-dap" },
  { "mfussenegger/nvim-lint" },
  { "stevearc/conform.nvim" },
  { "mfussenegger/nvim-dap-python" },
  { "linux-cultist/venv-selector.nvim", config = true },
  { "Vigemus/iron.nvim" },
  { "github/copilot.vim" },
  { "jackMort/ChatGPT.nvim", dependencies = { "nvim-lua/plenary.nvim", "nvim-telescope/telescope.nvim" } },
  { "nvimdev/dashboard-nvim" },
}
