#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
wiki_dir="${repo_root}/wiki"

if [ ! -d "${wiki_dir}" ]; then
	echo "Missing wiki directory: ${wiki_dir}"
	exit 1
fi

WIKI_DIR="${wiki_dir}" python3 - <<'PY'
import os
import re
import sys
from pathlib import Path

wiki_dir = Path(os.environ["WIKI_DIR"])
pattern = re.compile(r"\[[^\]]+\]\(([^)]+)\)")

# Links generated by wiki payload mirror (not committed in wiki/ source).
virtual_prefixes = ("Guide-", "Cheatsheet-")
virtual_pages = {"All-Docs"}

errors: list[str] = []

for md_file in sorted(wiki_dir.glob("*.md")):
    content = md_file.read_text(encoding="utf-8")
    for target in pattern.findall(content):
        target = target.strip()
        if not target:
            continue
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue

        target = target.split("#", 1)[0].split("?", 1)[0].strip()
        if not target:
            continue

        if target in virtual_pages or target.startswith(virtual_prefixes):
            continue

        candidates = []
        if target.endswith(".md"):
            candidates.append(wiki_dir / target)
        else:
            candidates.append(wiki_dir / target)
            candidates.append(wiki_dir / f"{target}.md")

        if not any(candidate.exists() for candidate in candidates):
            errors.append(f"{md_file.name}: broken wiki link target '{target}'")

if errors:
    print("Wiki source link checks failed:")
    for item in errors:
        print(f"- {item}")
    sys.exit(1)

print("Wiki source link checks passed")
PY
